sudo: required
language: php
  - 7.1
services:
  - docker

before_install:
  - docker build -t umutbariskarasar/lorem-ipsum-api -f Dockerfile-phpfpm .

before_script: 
  - cd web/api 
  - composer self-update
  - composer install

script: phpunit